apiVersion: v1
kind: Namespace
metadata:
  name: odoo-dev
---
#################################
#           Postgres            #
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: odoo-dev
data:
  POSTGRES_USER: "usr_odoo"
  PORTGRES_PASSWORD: "Q37zfHgsswMnYQnKPZG4XQ5p"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  namespace: odoo-dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/postgres-data-pv
    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: odoo-dev
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: odoo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-configmap
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: odoo-dev
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 15401
    targetPort: 5432
---

#################################
#             Odoo              #
#################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-configmap
data:
  HOST: "postgres-service"
  PORT: "15401"
  USER: "usr_odoo"
  PASSWORD: "Q37zfHgsswMnYQnKPZG4XQ5p"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-data-pv
  namespace: odoo-dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/odoo-data-pv
    server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-data-pvc
  namespace: odoo-dev
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  namespace: odoo-dev
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:16.0
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 8069
        envFrom:
        - configMapRef:
            name: odoo-configmap
        volumeMounts:
          - name: odoo-data
            mountPath: /var/lib/odoo
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  namespace: odoo-dev
spec:
  type: LoadBalancer
  selector:
    app: odoo
  ports:
  - port: 19801
    targetPort: 8069
