{{ $existingResource := lookup "v1" "Secret" $.Values.werf.namespace "azure-file-credentials" }}
{{ if not $existingResource }}
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-file-credentials
  namespace: {{ $.Values.werf.namespace }}
type: Opaque
stringData:
  azurestorageaccountname: {{ quote .Values.storage.accountName }}
  azurestorageaccountkey: {{ quote .Values.storage.accountKey }}
{{ end }}
