---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.client }}-{{ $.Values.appName }}-configmap
data:
  {{- range $key, $val := .Values.environmentVariables }}
    {{ $key }}: "{{ tpl $val $ }}"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.client }}-{{ $.Values.appName }}-odoo-conf
data:
  odoo.conf: |
    [options]
    db_host = {{ $.Values.database.hostname }}
    db_port = {{ $.Values.database.port }}
    db_name = {{ $.Values.database.name }}
    db_user = {{ $.Values.database.username }}
    db_password = {{ $.Values.database.password }}
    db_sslmode = prefer
    dbfilter =
    list_db = False
    db_template = template1
    data_dir = /var/lib/odoo/{{ $.Values.client | trim }}

    # Connection options
    workers = 6
    max_cron_threads = 1
    limit_memory_hard = 1677721600
    limit_memory_soft = 629145600
    limit_request = 8192
    limit_time_cpu = 240
    limit_time_real = 352
    limit_time_real_cron = 2400
    gevent_port = 8072

    # Demo Data options
    without_demo = all

    # HTTP options
    proxy_mode = True
