---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: {{ $.Values.client }}-{{ $.Values.odoo.persistentVolume.name }}
spec:
  capacity:
    storage: {{ .Values.odoo.persistentVolume.storageCapacity }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-premium
  csi:
    driver: file.csi.azure.com
    volumeHandle: "{{- printf "%s#%s#%s###%s" $.Values.storage.groupName $.Values.storage.accountName $.Values.odoo.persistentVolume.nfsFileShareName $.Values.werf.namespace -}}"
    volumeAttributes:
      protocol: nfs
      storageAccount: {{ $.Values.storage.accountName }}
      shareName: {{ $.Values.odoo.persistentVolume.nfsFileShareName }}
      server: {{ $.Values.storage.accountName }}.file.core.windows.net
    nodeStageSecretRef:
      name: azure-file-credentials
      namespace: {{ $.Values.werf.namespace }}
  volumeMode: Filesystem
