---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.client }}-{{ .Values.appName }}
spec:
  type: ClusterIP
  selector:
    app: {{ $.Values.client }}-odoo
  ports:
  - name: http-port
    port: {{ $.Values.odoo.port }}
    targetPort: 8069
  - name: gevent-port
    port: {{ $.Values.odoo.geventPort }}
    targetPort: 8072
